name: Generate Test Artifacts on GitHub-Hosted Runner
on: [push]
jobs:
  my-job:
    name: Run MATLAB Tests and Generate Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0
        env:
          MATHWORKS_TOKEN: ${{ secrets.MATHWORKS_TOKEN }}
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v0.2.0-test1
        with:
          source-folder: source
          test-results-junit: test-results/results.xml
          test-results-pdf: test-results/results.pdf
          code-coverage-cobertura: code-coverage/coverage.xml

