name: Use MATLAB in Workflow
on: [push]
jobs:
  my-job:
    name: Run MATLAB Commands
    runs-on: ubuntu-latest
    steps:
      # Install MATLAB on a GitHub-hosted runner
      - uses: matlab-actions/setup-matlab@v0
        env:
          MATHWORKS_TOKEN: ${{ secrets.MATHWORKS_TOKEN }}
        uses: matlab-actions/run-command@v0
        with:
            command: 'results = runtests, assertSuccess(results);'
